#!/bin/bash

set -eou pipefail

readonly SEED=1917
readonly DATA=../../data
readonly RANDOM_STARTS=25
LANGS=('ady' 'ara' 'arm_e' 'asm' 'bel' 'ben' 'bul' 'bur' 'ceb' 'dut' 'eng_us' 'fas' 'fre' 'geo' 'ger' 'gle'
	'gre' 'hbs_latn' 'hin' 'hun' 'ice' 'ind' 'ita' 'jpn_hira' 'khm' 'kor' 'lav' 'lit' 'lwl' 'mkd' 'mlt_latn' 'nno' 'per'
	'pus' 'rum' 'rus' 'shn' 'slv' 'spa' 'swe' 'tgl' 'tha' 'ukr' 'urd' 'vie_hanoi' 'wel' 'wel_sw')

mkdir -p checkpoints

for LANGUAGE in "${LANGS[@]}"; do
	TRAIN_TSV="${DATA}/${LANGUAGE}/${LANGUAGE}_train.tsv"
	DEV_TSV="${TRAIN_TSV//train/dev}"
	TEST_TSV="${TRAIN_TSV//train/test}"

	echo "Starting training for ${LANGUAGE}, using ${TRAIN_TSV}, ${DEV_TSV} and ${TEST_TSV}"
	# Output symbols.
	cut -f2 "${TRAIN_TSV}" "${DEV_TSV}" |
		ngramsymbols \
			>"${LANGUAGE}_phones.sym"
	# Alignments.
	python align.py \
		--seed="${SEED}" \
		--random_starts="${RANDOM_STARTS}" \
		--tsv_path="${TRAIN_TSV}" \
		--output_token_type="${LANGUAGE}_phones.sym" \
		--encoder_path="${LANGUAGE}.enc" \
		--far_path="${LANGUAGE}.far"
	# Loops over LM orders from 3 (trigram) to 9.
	for ORDER in $(seq 3 9); do
		# NGram model.
		echo "ORDER: ${ORDER}"
		./model \
			--encoder_path="${LANGUAGE}.enc" \
			--far_path="${LANGUAGE}.far" \
			--fst_path="checkpoints/${LANGUAGE}-${ORDER}.fst" \
			--order="${ORDER}"
		# Evaluation.
		./predict \
			--input_path="${DEV_TSV}" \
			--fst_path="checkpoints/${LANGUAGE}-${ORDER}.fst" \
			--output_token_type="${LANGUAGE}_phones.sym" \
			--output_path="${LANGUAGE}.txt"
		./evaluate \
			--gold_path="${DEV_TSV}" \
			--hypo_path="${LANGUAGE}.txt" \
			>"checkpoints/${LANGUAGE}-${ORDER}-dev.res"
		./predict \
			--input_path="${TEST_TSV}" \
			--fst_path="checkpoints/${LANGUAGE}-${ORDER}.fst" \
			--output_token_type="${LANGUAGE}_phones.sym" \
			--output_path="${LANGUAGE}.txt"
		./evaluate \
			--gold_path="${TEST_TSV}" \
			--hypo_path="${LANGUAGE}.txt" \
			>"checkpoints/${LANGUAGE}-${ORDER}-test.res"
	done
	rm "${LANGUAGE}_phones.sym" \
		"${LANGUAGE}.enc" \
		"${LANGUAGE}.far" \
		"${LANGUAGE}.txt"
done
