name: g2p-transformer-fairseq
channels:
 - conda-forge
 - pytorch
dependencies:
 - python=3.8.5
 - pytorch=1.6.0
 - fairseq=0.10.1
 - numpy=1.19.5
 - pandas=1.1.3
 - matplotlib=3.3.2
 - pandas=1.1.3
 - matplotlib=3.3.2
