#!/bin/bash

set -euo pipefail

# Fairseq expects six files:
# Two train, two dev, two test, each distinguished by prefixes.
# One file is the source and one is the target, distinguished by suffixes.
DATA="../../data"
LANGS=("ady" "arb" "arb_latin" "asm" "bel" "ben" "bul" "bul_latin" "ceb" "cym" "deu" "ell" "ell_latin" "eng_us"
	"fas_cls" "fas_cls_latin" "fra" "gle" "hbs" "hin" "hun" "hye" "hye_latin" "ind" "isl" "ita" "jpn" "kat" "khm" "kor"
	"kor_jamo" "lav" "lit" "lwl" "mkd" "mkd_latin" "mlt" "mya" "nld" "nno" "pes" "pol" "pus" "pus_latin" "ron" "rus"
	"rus_latin" "shn" "slv" "spa" "swe" "tgl" "tha" "uig" "uig_latin" "ukr" "ukr_latin" "urd" "urd_latin" "vie")

tsv() {
	for LANG in "${LANGS[@]}"; do
		for TASK in train dev test; do
			TSV="${DATA}/${LANG}/${LANG}_${TASK}.tsv"
			# Separates graphemes with spaces
			# Using python to avoid `sed` because `sed` operates on byte-level and messes up utf-8 encoding
			cut -f1 "${TSV}" |
				python -c "
import sys
for line in sys.stdin:
    print(' '.join(line.strip()))
            " >"${TASK}.${LANG}.graphemes"
			# Phonemes are already separated intelligently in WikiPron.
			cut -f2 "${TSV}" \
				>"${TASK}.${LANG}.phonemes"
		done
	done
}

bin() {
	for LANG in "${LANGS[@]}"; do
		fairseq-preprocess \
			--source-lang="${LANG}.graphemes" \
			--target-lang="${LANG}.phonemes" \
			--trainpref=train \
			--validpref=dev \
			--testpref=test \
			--tokenizer=space \
			--thresholdsrc=5 \
			--thresholdtgt=5 \
			--destdir="data-bin/${LANG}"
	done
}

main() {
	tsv
	bin
	rm -f -- *.{graph,phon}emes
}

main
